CC3 opdm
CrawfordGroup/pycc pull request #56
Opened 2023-02-07 17:37 UTC by zw0930

## Description
Adding CC3 one-particle density matrix for the calculation of dipole moments, useful in RT propagations.

## Todos
  - [ ] Adding CC3 terms to opdm in ccdensity;
  - [ ] Adding triple drivers for the nested loops over virtual orbitals for Doo (already in lambda_cc3 PR);
  - [ ] Modifying the dipole function in rtcc in terms of the contraction involving T1-transformed integrals;
  - [ ] Adding the test for electric dipole moments.

## Status
- [ ] Ready to go

2023-02-07 17:46 UTC, zw0930 commented
1. This branch includes all changes in lambda_cc3;
2. The new test (test_032) will replace test_031 after lambda_cc3 being merged;
3. The CC3 part of the density matrix is not generated automatically when ccdensity is initiated since it's relatively costly and not necessary when calculating dipole moments.

2023-02-14 21:01 UTC, lothian requested changes

2023-02-14 21:01 UTC, lothian commented on pycc/cclambda.py
> +                        Zmdfa[m] -= contract('dfe,ea->dfa', t3_lmn, L[n,l,v,v])
Same comment as above re: naming convention.

2023-02-14 22:04 UTC, lothian approved these changes

2023-02-14 22:04 UTC, merged